PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  SELECT DISTINCT ?band ?founded ?from ?homepage
  WHERE {
    
    ?band rdf:type dbo:Band.
?band dbo:genre dbr:Experimental_rock.
OPTIONAL { ?band foaf:homepage ?homepage  }.
OPTIONAL { ?band dbo:hometown ?from  }.
OPTIONAL { ?band dbo:activeYearsStartYear ?founded  }
    
  }

  ORDER BY ?band
  LIMIT 9
