PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX yago: <http://dbpedia.org/class/yago/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  SELECT DISTINCT ?band ?album ?albumDate ?member
  WHERE {
    
    ?band rdf:type dbo:Band.
?album rdf:type yago:Album106591815.
?album dbo:artist ?band.
?band dbo:genre dbr:Experimental_rock.
OPTIONAL { ?album dbo:releaseDate ?albumDate  }.
?band dbo:bandMember ?member
FILTER(?band NOT IN (<http://dbpedia.org/resource/Exists_(band)>))
    
  }

  ORDER BY ?band ?album
  LIMIT 10
